apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: jacky95183/spingboot-mall:latest  # 替換為你的 Docker Hub 鏡像
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/mall"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: myapp
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer